#ifndef CL_P_ERROR_H
#define CL_P_ERROR_H

/* General Syntax */

enum class ClErr {
  NULL_EXPRESSION                = 1,
  MISSING_OPEN_ROUND_BRACKET     = 2,
  MISSING_CLOSE_ROUND_BRACKET    = 3,
  MISSING_CLOSE_SQUARE_BRACKET   = 4,
  MISSING_COLON_OPERATOR         = 5,
  UNTERMINATED_STRING            = 6,
  MISSING_EXPONENTIAL_VALUE      = 7,
  INVALID_CHARACTER              = 8,
  MISSING_FUNCTION_NAME          = 9,
  EXTRA_FUNCTION_CHARS           = 10,
  STRUCT_SYNTAX_ERROR            = 11,
  STRUCT_DIM_SYNTAX_ERROR        = 12,
  INVALID_OPERATOR               = 13,
  INVALID_EXPRESSION             = 14,
  INVALID_UNARY_EXPRESSION       = 15,
  INVALID_BINARY_EXPRESSION      = 16,
  INVALID_ARRAY_SYNTAX           = 17,
  INVALID_LIST_SYNTAX            = 18,
  INVALID_DICT_SYNTAX            = 19,
  INVALID_FN_ARG_SYNTAX          = 20,

  /* Usage Syntax */

  INVALID_NO_FUNCTION_ARGS       = 21,
  INVALID_NO_ARRAY_SUBSCRIPTS    = 22,
  FUNCTION_NAME_CONFLICT         = 23,
  TOO_FEW_ARGUMENTS              = 24,
  TOO_MANY_ARGUMENTS             = 25,
  SUBSCRIPT_OUT_OF_RANGE         = 26,
  SUBSCRIPT_NOT_INTEGER          = 27,
  INVALID_TYPE_FOR_SUBSCRIPT     = 28,
  TOO_MANY_SUBSCRIPTS            = 29,
  INVALID_LVALUE_FOR_ASSIGNMENT  = 30,
  DIFFERENT_LENGTH_ARRAYS        = 31,
  INCOMPATIBLE_ARRAYS            = 32,
  ARRAY_FN_HAS_NON_ARRAY         = 33,
  ZERO_STRUCT_DIM                = 34,
  INVALID_STRUCT_VAR_NAME        = 35,
  MISSING_STRUCT_DIMS            = 36,
  INVALID_STRUCT_REF             = 37,
  INVALID_TYPE_FOR_OPERATOR      = 38,
  INVALID_TYPE_MIX               = 39,
  INVALID_VARIABLE_NAME          = 40,
  INVALID_FUNCTION_NAME          = 41,
  INVALID_STRUCT_NAME            = 42,
  MULTIPLE_DEF_FN_VARIABLE       = 43,
  INVALID_STRUCTURE_TYPE_NAME    = 44,
  INVALID_RHS_FOR_ASSIGNMENT     = 45,
  INVALID_DIMENSION              = 46,
  VALUE_OUT_OF_RANGE             = 47,

  /* Conversion */

  INVALID_STRING_TO_REAL_CONV    = 48,
  INVALID_ARRAY_TO_REAL_CONV     = 49,
  INVALID_LIST_TO_REAL_CONV      = 50,
  INVALID_DICT_TO_REAL_CONV      = 51,
  INVALID_STRUCT_TO_REAL_CONV    = 52,
  INVALID_STRING_TO_INTEGER_CONV = 53,
  INVALID_ARRAY_TO_INTEGER_CONV  = 54,
  INVALID_LIST_TO_INTEGER_CONV   = 55,
  INVALID_DICT_TO_INTEGER_CONV   = 56,
  INVALID_STRUCT_TO_INTEGER_CONV = 57,
  INVALID_REAL_TO_STRING_CONV    = 58,
  INVALID_INTEGER_TO_STRING_CONV = 59,
  INVALID_ARRAY_TO_STRING_CONV   = 60,
  INVALID_LIST_TO_STRING_CONV    = 61,
  INVALID_DICT_TO_STRING_CONV    = 62,
  INVALID_STRUCT_TO_STRING_CONV  = 63,
  INVALID_STRUCT_CONV            = 64,
  INVALID_ARRAY_STRUCT_CONV      = 65,
  INVALID_CONV_TO_ARRAY          = 66,
  INVALID_ARRAY_CONV             = 67,
  INVALID_CONVERSION             = 68,

  /* Evaluation */

  INVALID_LOG_VALUE              = 69,
  INVALID_SQRT_VALUE             = 70,
  INVALID_ASIN_VALUE             = 71,
  INVALID_ACOS_VALUE             = 72,
  DIVIDE_BY_ZERO                 = 73,
  NON_INTEGER_POWER_OF_NEGATIVE  = 74,
  ZERO_TO_NEG_POWER_UNDEF        = 75,
  NEGATIVE_POWER                 = 76,
  POWER_FAILED                   = 77,
  USER_FUNCTION_FAILED           = 78,

  /* Undefined */

  UNDEFINED_FUNCTION             = 79,
  UNDEFINED_VARIABLE             = 80,
  UNDEFINED_STRUCT_TYPE          = 81,
  UNDEFINED_VALUE                = 82,
  UNDEFINED_SUBSCRIPT_VALUE      = 83,
  UNDEFINED_ASSIGN_VALUE         = 84
};

#define ClErrThrow(e) CITHROW(int(e))

#endif
