#ifndef CL_P_ERROR_H
#define CL_P_ERROR_H

/* General Syntax */

#define CLERR_NULL_EXPRESSION                1
#define CLERR_MISSING_OPEN_ROUND_BRACKET     2
#define CLERR_MISSING_CLOSE_ROUND_BRACKET    3
#define CLERR_MISSING_CLOSE_SQUARE_BRACKET   4
#define CLERR_MISSING_COLON_OPERATOR         5
#define CLERR_UNTERMINATED_STRING            6
#define CLERR_MISSING_EXPONENTIAL_VALUE      7
#define CLERR_INVALID_CHARACTER              8
#define CLERR_MISSING_FUNCTION_NAME          9
#define CLERR_EXTRA_FUNCTION_CHARS           10
#define CLERR_STRUCT_SYNTAX_ERROR            11
#define CLERR_STRUCT_DIM_SYNTAX_ERROR        12
#define CLERR_INVALID_OPERATOR               13
#define CLERR_INVALID_EXPRESSION             14
#define CLERR_INVALID_UNARY_EXPRESSION       15
#define CLERR_INVALID_BINARY_EXPRESSION      16
#define CLERR_INVALID_ARRAY_SYNTAX           17
#define CLERR_INVALID_LIST_SYNTAX            18
#define CLERR_INVALID_DICT_SYNTAX            19
#define CLERR_INVALID_FN_ARG_SYNTAX          20

/* Usage Syntax */

#define CLERR_INVALID_NO_FUNCTION_ARGS       21
#define CLERR_INVALID_NO_ARRAY_SUBSCRIPTS    22
#define CLERR_FUNCTION_NAME_CONFLICT         23
#define CLERR_TOO_FEW_ARGUMENTS              24
#define CLERR_TOO_MANY_ARGUMENTS             25
#define CLERR_SUBSCRIPT_OUT_OF_RANGE         26
#define CLERR_SUBSCRIPT_NOT_INTEGER          27
#define CLERR_INVALID_TYPE_FOR_SUBSCRIPT     28
#define CLERR_TOO_MANY_SUBSCRIPTS            29
#define CLERR_INVALID_LVALUE_FOR_ASSIGNMENT  30
#define CLERR_DIFFERENT_LENGTH_ARRAYS        31
#define CLERR_INCOMPATIBLE_ARRAYS            32
#define CLERR_ARRAY_FN_HAS_NON_ARRAY         33
#define CLERR_ZERO_STRUCT_DIM                34
#define CLERR_INVALID_STRUCT_VAR_NAME        35
#define CLERR_MISSING_STRUCT_DIMS            36
#define CLERR_INVALID_STRUCT_REF             37
#define CLERR_INVALID_TYPE_FOR_OPERATOR      38
#define CLERR_INVALID_TYPE_MIX               39
#define CLERR_INVALID_VARIABLE_NAME          40
#define CLERR_INVALID_FUNCTION_NAME          41
#define CLERR_INVALID_STRUCT_NAME            42
#define CLERR_MULTIPLE_DEF_FN_VARIABLE       43
#define CLERR_INVALID_STRUCTURE_TYPE_NAME    44
#define CLERR_INVALID_RHS_FOR_ASSIGNMENT     45
#define CLERR_INVALID_DIMENSION              46
#define CLERR_VALUE_OUT_OF_RANGE             47

/* Conversion */

#define CLERR_INVALID_STRING_TO_REAL_CONV    48
#define CLERR_INVALID_ARRAY_TO_REAL_CONV     49
#define CLERR_INVALID_LIST_TO_REAL_CONV      50
#define CLERR_INVALID_DICT_TO_REAL_CONV      51
#define CLERR_INVALID_STRUCT_TO_REAL_CONV    52
#define CLERR_INVALID_STRING_TO_INTEGER_CONV 53
#define CLERR_INVALID_ARRAY_TO_INTEGER_CONV  54
#define CLERR_INVALID_LIST_TO_INTEGER_CONV   55
#define CLERR_INVALID_DICT_TO_INTEGER_CONV   56
#define CLERR_INVALID_STRUCT_TO_INTEGER_CONV 57
#define CLERR_INVALID_REAL_TO_STRING_CONV    58
#define CLERR_INVALID_INTEGER_TO_STRING_CONV 59
#define CLERR_INVALID_ARRAY_TO_STRING_CONV   60
#define CLERR_INVALID_LIST_TO_STRING_CONV    61
#define CLERR_INVALID_DICT_TO_STRING_CONV    62
#define CLERR_INVALID_STRUCT_TO_STRING_CONV  63
#define CLERR_INVALID_STRUCT_CONV            64
#define CLERR_INVALID_ARRAY_STRUCT_CONV      65
#define CLERR_INVALID_CONV_TO_ARRAY          66
#define CLERR_INVALID_ARRAY_CONV             67
#define CLERR_INVALID_CONVERSION             68

/* Evaluation */

#define CLERR_INVALID_LOG_VALUE              69
#define CLERR_INVALID_SQRT_VALUE             70
#define CLERR_INVALID_ASIN_VALUE             71
#define CLERR_INVALID_ACOS_VALUE             72
#define CLERR_DIVIDE_BY_ZERO                 73
#define CLERR_NON_INTEGER_POWER_OF_NEGATIVE  74
#define CLERR_ZERO_TO_NEG_POWER_UNDEF        75
#define CLERR_NEGATIVE_POWER                 76
#define CLERR_POWER_FAILED                   77
#define CLERR_USER_FUNCTION_FAILED           78

/* Undefined */

#define CLERR_UNDEFINED_FUNCTION             79
#define CLERR_UNDEFINED_VARIABLE             80
#define CLERR_UNDEFINED_STRUCT_TYPE          81
#define CLERR_UNDEFINED_VALUE                82
#define CLERR_UNDEFINED_SUBSCRIPT_VALUE      83
#define CLERR_UNDEFINED_ASSIGN_VALUE         84

#endif
